baseURL = "https://python-poetry.org/"
languageCode = "en-us"
title = "Poetry - Python dependency management and packaging made easy"

theme = "poetry"

ignoreFiles = ["^assets/src"]
pygmentsUseClasses = true

[params]
description = "Python dependency management and packaging made easy"

[params.documentation]
versions = ["master", "1.1"]
defaultVersion = "1.1"


[markup.goldmark.renderer]
unsafe = true
